[bluesense]
prometheus="http://alexchi-raspi.local:9090/"
job="bluesense_shanghai_changning"
instant_push=false
site_name="Changning, Shanghai"

[telegram]
bot_token="test:test"
chat_id=-10023333333
log_chat_id=-10023333333

[plot]
fontface="/Library/Fonts/Arial Unicode.ttf"

[exporter]
addr=":9400"
