[mrsans]
bluesense_url="http://alexchi-raspi.local:9090/"
prometheus_url="http://alexchi-raspi.local:9090/"
bluesense_job="bluesense_shanghai_changning"
telegram_bot_token="test"
telegram_chat_id=23333333
telegram_log_chat_id=233333333
plot_fontface="/Library/Fonts/Arial Unicode.ttf"
instant_push=false
site_name="Changning, Shanghai"
prometheus_addr=":9400"
